# docker-compose.yml для ControllerBot-лайт 2.0

version: "3.9"

services:
  bot:
    build: .
    container_name: controllerbot
    env_file:
      - ./deploy/.env.example
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: controllerbot_db
    environment:
      POSTGRES_USER: controllerbot
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: controllerbot_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
